# https://docs.buf.build/ci-cd/github-actions
name: storybook_tests
on:
  pull_request_review:
    types:
      submitted
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review # need this as we will skip the test on draft PRs to save cost.
  # Run on master continuously to catch any issues on HEAD.
  push:
    branches:
      - main
concurrency:
  # we use pr number for pull request, and sha for push so we can run on every commit.
  # Note: cancel is considered as failure on master check status.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  # The requirement_check step is needed so we can mark the storybook_test as required on repo level.
  # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  requirement_check:
    # Run storybook check only for non-draft PRs and post-approval.
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false) || (github.event_name == 'pull_request_review' && github.event.pull_request.review.state == 'APPROVED') }}
    permissions:
      pull-requests: read
      contents: read
    # Use ubuntu so it costs less, this step will run on all PRs.
    runs-on: ubuntu-latest
    outputs:
      # macos runner is expensive, so we don't run it on drafts - its recommended for eng to run storybook locally before sending out your PR.
      should_run_storybook: ${{ steps.filter.outputs.storybook }}
      approved: ${{ steps.review_status.outputs.result == 'true' }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' }}
        with:
          sparse-checkout: |
            typescript
            data
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # The conditions are `any()` so any of the patterns match will return true.
          filters: |
            storybook:
              - pnpm-lock.yaml
              - typescript/!(tools)/!(internal|debug)/**
              - typescript/!(tools)/*
              - typescript/*
      - uses: actions/github-script@v7
        if: ${{ github.event_name == 'pull_request' }}
        id: review_status
        with:
          result-encoding: string
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            })
            console.log(reviews)
            return reviews.data.some((review) => review.state === 'APPROVED')
  storybook_test:
    needs: [requirement_check]
    # Run on master commits or PRs that we want to run storybook tests.
    if: ${{ success() && needs.requirement_check.outputs.should_run_storybook == 'true' && needs.requirement_check.outputs.approved == 'true'  }}
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/running-jobs-on-larger-runners
    runs-on: ubuntu-latest 
    # should finish ~6 min, 10 min max for -large
    # need to increase to 25 min for standard
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            typescript
            data

      - run: |
          echo "will run test"