# https://docs.buf.build/ci-cd/github-actions
name: storybook_tests
on:
  pull_request:
    branches:
      - master
      - fe-release-**
    types:
      - opened
      - synchronize
      - reopened
      # Need following as we will skip the test on draft / and not yet requested PRs to save cost.
      # intentionally left out converted_to_draft and review_request_removed as we do not
      # want to rerun the check just for those (they don't change anything already run).
      - ready_for_review
      - review_requested
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  # The requirement_check step is needed so we can mark the storybook_test as required on repo level.
  # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  requirement_check:
    # We skip this check completely on draft PRs.
    if: ${{ github.event.pull_request.draft == false }}
    permissions:
      pull-requests: read
      contents: read
    # Use ubuntu so it costs less, this step will run on all PRs.
    runs-on: ubuntu-latest
    outputs:
      # macos runner is expensive, so we don't run it on drafts - its recommended for eng to run storybook locally before sending out your PR.
      should_run_storybook: ${{ fromJson(steps.pr_requirements.outputs.result).should_run_storybook }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          # The conditions are `any()` so any of the patterns match will return true.
          filters: |
            storybook:
              - pnpm-lock.yaml
              - typescript/!(tools)/!(internal|debug)/**
              - typescript/!(tools)/*
              - typescript/*
      - uses: actions/github-script@v7
        if: ${{ steps.filter.outputs.storybook }}
        id: pr_requirements
        with:
          github-token: ${{ secrets.TEMP_TOKEN}}
          script: |
            const result = {
              should_run_storybook: false,
            }
            const action = context.action
            if (action === "review_requested") {
              result.should_run_storybook = context.payload.requested_reviewers.length > 0
            } else {
              result.should_run_storybook = context.payload.pull_request.requested_reviewers.length > 0
              if (!result.should_run_storybook) {
                const reviews = await github.rest.pulls.listReviews({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number,
                })
                result.should_run_storybook = reviews.data.length > 0
              }
            }
            console.log(result, context.payload)
            return result
  storybook_test:
    needs: [requirement_check]
    # Run on master commits or PRs that we want to run storybook tests.
    if: ${{ success() && needs.requirement_check.outputs.should_run_storybook == 'true' }}
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/running-jobs-on-larger-runners
    runs-on: ubuntu-latest
    # should finish ~6 min, 10 min max for -large
    # need to increase to 25 min for standard
    timeout-minutes: 10

    steps:
      - run: echo "will run"